### ISSUE TITLE
Wrench durability does not decrease

### ISSUE THREAD

**Issue by discoguillotine** [CreeperMagnet/the-creepers-code#101] opened 2022-03-12 22:14 UTC
During development, wrench durability was removed, but during the process of re-adding it, something was done improperly. Durability shows in lore but does not go down.

**Comment by HingeDH** [comment] 2022-03-12 22:19
Wrench durability was re-added due to the mending and unbreaking enchantments. The bug here is actually that the durability does not decrease

**Comment by CreeperMagnet** [comment] 2022-03-12 22:31
Works as intended

**Comment by CreeperMagnet** [comment] 2022-03-21 06:30
Fixed in V1.0.1.

**Closed by CreeperMagnet** 2022-03-21 06:30 UTC
Labels: priority: medium
