### ISSUE TITLE
Suspicious blocks as items contain wrong component and because of that do not contain loot

### ISSUE THREAD

**Issue by magmamir** [CreeperMagnet/the-creepers-code#244] opened 2024-08-05 05:53 UTC
1.3.6 for 1.21 Version.
Long story short, in your husk and piglin bartering loot tables you use set_component function with minecraft:container_loot component, but suspicious blocks do not have that one:
`{
  "function": "minecraft:set_components",
    "components": {
      "minecraft:container_loot": {
        "loot_table": "tcc:archaeology/husk_drop",
        "seed": 0
      }
    }
}`
Instead you should use usual block_entity_data like that:
`{
  "function": "minecraft:set_components",
  "components": {
    "minecraft:block_entity_data": {
      "id": "minecraft:brushable_block",
      "LootTable" : "tcc:archaeology/husk_drop"
    }
  }
}`
That should work.. probably. Or not. Sorry, it's already a morning for me and i didn't sleep a night, i could messed up somewhere.

**Comment by CreeperMagnet** [comment] 2024-08-05 12:08
Duplicate of #231

**Closed** 2024-08-05 12:08 UTC
